### ISSUE TITLE
Rename files starting with Mp3 to MP3

### ISSUE THREAD

**Issue by ghost** [ZaneDubya/MP3Sharp#11]
https://github.com/ZaneDubya/MP3Sharp/blob/master/MP3Sharp/MP3Sharp.csproj#L119
```
    <Compile Include="MP3SharpException.cs" />
    <Compile Include="MP3Stream.cs" />
```
 
The files in the repository:
https://github.com/ZaneDubya/MP3Sharp/blob/master/MP3Sharp/Mp3SharpException.cs
https://github.com/ZaneDubya/MP3Sharp/blob/master/MP3Sharp/Mp3Stream.cs 

Causes a compilation error at least on Linux system.

```
CSC : error CS2001: Source file 'MP3Sharp/MP3Sharp/MP3SharpException.cs' could not be found. [MP3Sharp/MP3Sharp/MP3Sharp.csproj]
CSC : error CS2001: Source file 'MP3Sharp/MP3Sharp/MP3Stream.cs' could not be found. [MP3Sharp/MP3Sharp/MP3Sharp.csproj]
```

Compilation error is fixed when files are renamed from `Mp3` to `MP3`.

**Comment by ZaneDubya** [comment]
Fascinating the things that windows lets me get away with. Thanks for the fix @samuliy!
