### ISSUE TITLE
Skip ID3v2 tags without unsynchronisation.

### ISSUE THREAD

**Issue by Juvwxyz** [ZaneDubya/MP3Sharp#14]
A ID3v2 tag without unsynchronisation may contain frame sync (0xFFF or 0xFFE), which may led false decodeing. Should we skip it in this library or let the user deal with it themselves?

**Comment by ZaneDubya** [comment]
Hello! Could you upload an example? Or send it to me at zanewagner@gmail.com. Many many thanks. -Zane

**Comment by Juvwxyz** [comment]
> Hello! Could you upload an example? Or send it to me at [zanewagner@gmail.com](mailto:zanewagner@gmail.com). Many many thanks. -Zane

Sure, you can download an example here: [mp3 file with frame sync inside id3 tag](https://card.niconi.co.ni/asset/assets/sound/voice/navi/vo_li_203_0001.mp3).
The MP3Sharp library cannot decode it corectly if you don't skip the id3 tag.
To fix this is simple, just skip the tag in the constructor. Or can I open a pull request?

**Comment by ZaneDubya** [comment]
You are welcome to open a pull request. :) If you don't, I will try to take a look this weekend.

**Comment by ZaneDubya** [comment]
I see it, thank you. Will review this weekend. :)

**Comment by ZaneDubya** [comment]
Looks great - thanks!
