### ISSUE TITLE
Error loading most of mp3 files, when opening mp3 file it only get less than minute of samples

### ISSUE THREAD

**Issue by ghost** [ZaneDubya/MP3Sharp#16]
Hello,
Currently I am working on a project that play audio, project repository can be found here: <https://github.com/alaahadid/Agile-Player>.
Basically it plays pcm audio data in new unique way. It include wave format as default and work perfect.
I attempted to add mp3 support as media format, the point is to read mp3 data and convert them into pcm data then send them into the player to play them.
I found this repository and i included MP3Sharp into the project, <https://github.com/alaahadid/Agile-Player/tree/main/source/Formats> and <https://github.com/alaahadid/Agile-Player/blob/main/source/Formats/Formats/FormatMP3.cs>.
The format implementation in player (FormatMP3.cs) is simply uses `MP3Strame` to open file, then get sample-by-sample and send them into the player engine. The issues are:
1. It fails with most of the files in `CheckFile(string filePath) `method, in  `MP3Stream st = new MP3Stream(filePath);` it throw an exception.
2. **Update: i fixed this issue by loading the whole mp3 stream into memory stream then plays from memory stream.**

 _It get wrong pcm data length if it successfully opened, i.e. Wrong length in second, see `LoadFile(string filePath) `method, i used this line to calculate song length in seconds: `Length = read_stream.Length / (BlockAlign * read_stream.Frequency);`_

It can read full song length now, i hope if there will be a faster way to get the song length in seconds.

Please help, it would be great if it is work with my project !!
Regards
Alaa

**Comment by ZaneDubya** [comment]
Hi Alaa, apologies for not getting back to this. It looks like your user account was deleted. : (
