### ISSUE TITLE
[Bug] Exception when opening come MP3 files

### ISSUE THREAD

**Issue by Drake53** [ZaneDubya/MP3Sharp#20]
In some files I get an exception in CheckAndSkipId3Tag(), because id3_tag_size (in the example 264182) is larger than the size of _TemporaryBuffer in PushbackStream (4096).
Example file: https://vgmsite.com/soundtracks/la-mulana-remake-original-soundtrack/vxsclqrx/1-03%20Mr.%20Explorer.mp3

**Comment by ZaneDubya** [comment]
Thanks! I should be able to fix this easily.

**Comment by ZaneDubya** [comment]
Easy fix in, just need to test it a bit.
