### ISSUE TITLE
[Bug] MP3Stream.IsEOF remains true after resetting Position

### ISSUE THREAD

**Issue by Drake53** [ZaneDubya/MP3Sharp#22]
This bug is actually not in this repo but in the nuget package https://www.nuget.org/packages/MP3Sharp which is based on this fork: https://github.com/Nihlus/MP3Sharp
The fork doesn't have issues enabled so I'm putting it here, I hope you don't mind
@Nihlus

Also it's kind of confusing that the nuget package is based on a fork instead of the main repository, have you considered making your own nuget package?

**Comment by Nihlus** [comment]
I'd gladly turn over the package and its maintenance to this repo - I don't really have time to keep up with this project due to other responsibilities.

**Comment by ZaneDubya** [comment]
Thanks!

**Comment by ZaneDubya** [comment]
Hello,

I'm not interested in running a nuget package. As Nihlus points out, it's time and responsibility to keep up with; I don't have much of the first and don't want much of the second.

Check here for updates. Thanks!
