### ISSUE TITLE
Low quality read data

### ISSUE THREAD

**Issue by Khhs167** [ZaneDubya/MP3Sharp#24]
I am currently setting up an audio system, and the read PCM data from the MP3Stream is really low quality. I don't know what, here's the main read function:
```cs
handle = AL.GenBuffer();
		
MemoryStream dataStream = new MemoryStream(data); // Data is the data of the mp3 file, just read using File.ReadAllBytes
MP3Stream mp3Stream = new MP3Stream(dataStream);
MemoryStream memoryStream = new MemoryStream();
mp3Stream.CopyTo(memoryStream);

AL.BufferData(handle, mp3Stream.Format == SoundFormat.Pcm16BitMono ? ALFormat.Mono16 : ALFormat.Stereo16, memoryStream.ToArray(), mp3Stream.Frequency);
```

I'm attaching the file inputted and a short snippet of how it sounds, they are from the persona 5 soundtrack so if they're removed, I wouldn't be surprised
[input-output.zip](https://github.com/ZaneDubya/MP3Sharp/files/10816064/input-output.zip)

**Comment by ZaneDubya** [comment]
Hey @Khhs167 !

Thanks for including the input and output files. That made it a lot easier to test this report.

Your output file is missing a lot of the high end; most of everything above 14 kHz and everything above 16 kHz is missing. But I don't think it is MP3Sharp doing this.

On my end, your input file sounds the same when rendered by MP3Sharp and the macOS MP3 preview feature.

It might be your AL library. Maybe. I am not sure. But it is working fine on this end.

Sorry I can't be of more help!
