### ISSUE TITLE
On some MP3 files this exception happens (on Read function of MP3 Stream)

### ISSUE THREAD

**Issue by aghajani** [ZaneDubya/MP3Sharp#3]
IndexOutOfRangeException: Array index is out of range.
MP3Sharp.Decoding.Decoders.LayerIIIDecoder.HuffmanDecode (Int32 ch, Int32 gr)
MP3Sharp.Decoding.Decoders.LayerIIIDecoder.Decode ()
MP3Sharp.Decoding.Decoders.LayerIIIDecoder.DecodeFrame ()
MP3Sharp.Decoding.Decoder.DecodeFrame (MP3Sharp.Decoding.Header header, MP3Sharp.Decoding.Bitstream stream)
MP3Sharp.MP3Stream.ReadFrame ()
MP3Sharp.MP3Stream.Read (System.Byte[] buffer, Int32 offset, Int32 count)

and here is the MediaInfo of the MP3 file causing this exception:
General
Format                      : MPEG Audio
File size                   : 11.0 MiB
Duration                    : 4mn 22s
Overall bit rate mode       : Constant
Overall bit rate            : 320 Kbps
Part/Position               : 1
Part/Total                  : 9
Track name/Position         : 1
Track name/Total            : 9

Audio
Format                      : MPEG Audio
Format version              : Version 1
Format profile              : Layer 3
Mode                        : Joint stereo
Mode extension              : MS Stereo
Duration                    : 4mn 22s
Bit rate mode               : Constant
Bit rate                    : 320 Kbps
Channel(s)                  : 2 channels
Sampling rate               : 44.1 KHz
Compression mode            : Lossy
Stream size                 : 10.00 MiB (91%)

**Comment by DamianMehers** [comment]
This may be fixed by my [pull request](https://github.com/ZaneDubya/MP3Sharp/pull/8)
