### ISSUE TITLE
XNA4Sample repeat not working.

### ISSUE THREAD

**Issue by JavidPack** [ZaneDubya/MP3Sharp#4]
Attempting "mp3.Play(true);" in BaseGame.cs will not repeat the playback.

Line 280 in BitStream.cs throws an error:

Exception thrown: 'MP3Sharp.Decoding.BitstreamException' in MP3Sharp.dll
Additional information: Bitstream errorcode 4 (this is STREAM_EOF)

It looks like IsEOF is set to true, causing all the code in XNAMP3.cs Line 100 (The if (m_Repeat) block) to fail since read will return 0 immediately if IsEOF.

**Comment by ZaneDubya** [comment]
Fixed in #10.
