### ISSUE TITLE
How do you actually play the mp3?

### ISSUE THREAD

**Issue by eschneider999** [ZaneDubya/MP3Sharp#6]
I see you pic show the PCMAudioDevice, where is that?

**Comment by ZaneDubya** [comment]
Hi @eschneider999 !

You need an API that allows you to submit a PCM buffer to a device! NAudio and XNA are two examples. You should also be able to use the WaveOut interface.

**Comment by eschneider999** [comment]
I just tried NAudio, doesn't work in core.
Could not load file or assembly 'System.Windows.Forms

Also if I could use NAudio, why would I need this lib?

**Comment by ZaneDubya** [comment]
Sorry, I'm not sure what interface you might have available.
> Also if I could use NAudio, why would I need this lib?

Fair point!
