### ISSUE TITLE
Extract left and right track samples

### ISSUE THREAD

**Issue by AngeloMascaro** [ZaneDubya/MP3Sharp#7]
Hi ZaneDubya
I get these byte[] buffers, but in order to process the audio file I need to extract from them the left and the right 16 bit samples. 
How can I do it? _Buffer is private, ReadBuffer is private...

**Comment by ZaneDubya** [comment]
This is not in scope. However, since the output is 16bit, you can expect that the output stream will be 2 bytes of one channel, then 2 bytes of the other channel, then 2 bytes of the first channel, etc., etc.
