### ISSUE TITLE
What is PCMAudioDevice you used in code ?

### ISSUE THREAD

**Issue by NothingFaceX** [ZaneDubya/MP3Sharp#9]
Hi , what is PCMAudioDevice you used in code and how can I get it ?

**Comment by ZaneDubya** [comment]
It would be any audio device that can accept a PCM bitstream.

https://www.google.com/search?client=safari&rls=en&q=c%23+pcm+stream+play&ie=UTF-8&oe=UTF-8

**Comment by NothingFaceX** [comment]
I know man , so it was only a fake example ? I mean you made it for saying this way this things works or PCMAudioDevice  is a thing ? :D 
is there anything you see good for merging with Mp3Sharp ?
I used it with NAudio WaveOut but it only play 2 second of it :\

**Comment by ZaneDubya** [comment]
It is just an example.

Are you checking if the pending buffer count is empty? You need to generate the PCM data and feed the buffer to the PCM device on a continuing basis until the song is over.

**Comment by NothingFaceX** [comment]
I post full code I can't figure it out it's from Mp3Sharp or WaveOut there's nothing in debugger

**Comment by NothingFaceX** [comment]
Hi again , I checked out and WaveOut was working correctly and issue is from Mp3Sharp
it only parse 2 second of my mp3 file but i can't say it's bug or I'm using code wrong !

this is what I use :
```
MemoryStream memory_stream = new MemoryStream(audio_mp3_byte);
var stream = new MP3Stream(memory_stream);
byte[] soundparse = new byte[audio_mp3_byte.Length];
stream.Read(soundparse, 0, audio_mp3_byte.Length);
```
audio_mp3_byte is a byte array of a 10 second mp3 file

thanks

**Comment by ZaneDubya** [comment]
What is audio_mp3_byte?

**Comment by ZaneDubya** [comment]
Hi NothingFaceX, 

MP3Stream does not decompress the entire MP3 all at once, because this would take 30+ mb for a 3 minute song. Instead it only decompresses a small portion and expects that you will submit more data later. 

Are you sure you are checking the MP3Stream to see if it needs more data?

**Comment by ZaneDubya** [comment]
As an example --- here you would be calling Update regularly until the song is done.

```
        private MP3Stream _Stream;
        private const int NUMBER_OF_PC_BYTES_TO_READ_PER_CHUNK = 0x8000; // 32768 bytes, about 0.9 seconds at 128kbs
        private readonly byte[] _WaveBuffer = new byte[NUMBER_OF_PC_BYTES_TO_READ_PER_CHUNK];
        private bool _Repeat;
        private bool _Playing;

        public void Update() {
            // if the buffer empties, the music will stop playing. Thus we must continually check if it is empty.
            OnBufferNeeded(null, null);
        }

        private override void OnBufferNeeded(object sender, EventArgs e) {
            if (_Playing) {
                while (_ThisInstance.PendingBufferCount < 3) {
                    byte[] buffer = GetBuffer();
                    if (_ThisInstance?.IsDisposed ?? true) {
                        return;
                    }
                    _ThisInstance.SubmitBuffer(buffer);
                }
            }
        }

        private byte[] GetBuffer() {
            if (_Playing) {
                int bytesReturned = _Stream.Read(_WaveBuffer, 0, _WaveBuffer.Length);
                if (bytesReturned != NUMBER_OF_PC_BYTES_TO_READ_PER_CHUNK) {
                    if (_Repeat) {
                        _Stream.Position = 0;
                        _Stream.Read(_WaveBuffer, bytesReturned, _WaveBuffer.Length - bytesReturned);
                    }
                    else {
                        if (bytesReturned == 0) {
                            Stop();
                        }
                    }
                }
                return _WaveBuffer;
            }
            Stop();
            return null;
        }

        public void BeforePlay() {
            if (_Playing) {
                Stop();
            }
            try {
                Stream stream = CanoResourceProvider.FileSystem.GetFileStream(Path);
                _Stream = new MP3Stream(stream, NUMBER_OF_PC_BYTES_TO_READ_PER_CHUNK);
                Frequency = _Stream.Frequency;
                _Playing = true;
            }
            catch (Exception e) {
                // file in use or access denied.
                Tracer.Error(e.ToString());
                _Playing = false;
            }
        }

        public void AfterStop() {
            if (_Playing) {
                _Playing = false;
                _Stream.Close();
                _Stream = null;
            }
        }
```

**Comment by NothingFaceX** [comment]
Thank you ZaneDubya , I believe your method can be really complicated for a normal C# app , not a game.
I just found out NAudio has a mp3 to PCM and it works just fine with any length and memory management.
I don't know if you're still interested in your library but I believe you can improve it to a "production ready" library.

thanks again for your time...
